### ISSUE TITLE
Images are stretched vertically on Chrome

### ISSUE THREAD

**Issue by AmeliaWellers** [matthewcrist/ctoec#60]
**Describe the bug**
Some images look stretched out vertically in Chrome on the live site. Adam was able to replicate. The image seems to be about double the vertical length that is should be. 

**To Reproduce**
1. Visit any page with an image on either the stage or the live sites, such as the [About Page.](https://www.ctoec.org/about-oec/) 

**Expected behavior**
Image dimension ratio (L x W) on the webpage should match the image dimensions of the uploaded image file and scale proportionately across devices.

**Screenshots**
[Screen Shot 2021-01-27 at 4.57.01 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/7f6b9b0c-2b8a-42be-80dc-cd9f9922b611)

**Desktop**
 - Browser: Replicated in Chrome: desktop, mobile and tablet view.

**Additional context**
Places to explore: 
-  likely related to Jesse's plugin updates last night
- something to do with the latest Gutenberg version updates

**Comment by bloom-hondo** [comment]
This is fixed.

**Comment by AmeliaWellers** [comment]
@bloom-hondo I'm afraid it's not resolved yet. I checked this page: https://www.ctoec.org/become-a-provider/ and the image are still stretched vertically in both Safari and Chrome.

**Comment by bloom-hondo** [comment]
@AmeliaWellers can you try in a private window? I just dumped the cache.

<img width="1290" alt="Screen Shot 2021-01-28 at 10 39 10 AM" src="https://user-images.githubusercontent.com/53876248/106161674-4a347b80-6155-11eb-948b-c539231187ae.png">

**Comment by AmeliaWellers** [comment]
Perfect. It works in incognito in both Safari and Chrome. Thank you!

**Comment by AmeliaWellers** [comment]
Reopening this one because there's still a case of a stretched image @bloom-hondo 
**issue**: when the Media & Text block is selected, the image stretches vertically again. This is most likely the same issue that broke the videos/images, but just one more case.

**Comment by bloom-hondo** [comment]
Is there a URL with an example?

**Comment by AmeliaWellers** [comment]
My apologies. I've been keeping a draft going in production (that I will eventually remove) to test out the gutenberg changes. The page title is "[a draft page for testing the new editor](https://www.ctoec.org/?page_id=12798&preview=true#heading)" and here's a screen shot: ![Screen Shot 2021-02-11 at 4.41.43 PM.png](https://images.zenhubusercontent.com/600707487eacdcc9a535ffa4/7cfa7883-0c30-4081-a0de-e58960697e30)

**Comment by AmeliaWellers** [comment]
Adding one more example: https://www.ctoec.org/about-oec/partnerships/parent-cabinet/parent-cabinet-history/ 

This is going live soon, and this format for the bios seems to be the cleanest (when the images are not stretched) and easiest to manage, compared to manually dragging and shaping the boxes. Will check on Monday about if it's possible to bring this into Release 0.2
